--- name:default
# Cycle time in seconds
cycle_time: 0.01

# The limits for the joints
limits:
  names: ["J_Foot"]
  elements: 
      - max: 
          position: 1.0
          speed: 0.5
          effort: 0.1
        min: 
          position: -1.0
 

# Set output effort as input for next cycle
override_input_effort: true

# Set output position as input for next cycle
override_input_position: false

# Set output speed as input for next cycle
override_input_speed: false

# The synchronization behavior of RML. Can be one of 0 = RMLFlags::PHASE_SYNCHRONIZATION_IF_POSSIBLE,
# 1 = RMLFlags::ONLY_TIME_SYNCHRONIZATION, 2 = RMLFlags::ONLY_PHASE_SYNCHRONIZATION, 3 = RMLFlags::NO_SYNCHRONIZATION
sync_behavior: 1

# Behavior when reaching positional limits. Can be one of 0 = RMLFlags::POSITIONAL_LIMITS_IGNORE,
# 1 = RMLFlags::POSITIONAL_LIMITS_ERROR_MSG_ONLY, 2 = RMLFlags::POSITIONAL_LIMITS_ACTIVELY_PREVENT
# Only available for Reflexxes Type_IV 
positional_limits_behavior: 2
