--- name:default
# Cycle time in seconds
cycle_time: 0.02

# The limits for the joints
limits:
  names: ["J_Foot"]
  elements: 
       - max: 
          position: 10.0
          speed: 1.0
          effort: 1.0
         min: 
          position: -10.0

# Maximum change of acceleration. Size has to be the same as limits
max_jerk: [1.0]

# Set output effort as input for next cycle
override_input_effort: true

# Set output position as input for next cycle
override_input_position: true

# Set output speed as input for next cycle
override_input_speed: true

# Set output speed to fixed value every time. Setting this value to NaN means no override.
override_output_effort: .nan

# Set output speed to fixed value every time. Setting this value to NaN means no override.
override_output_speed: .nan

# Set target velocity forcefully to this value
override_target_velocity: 0.5

# Behavior when reaching positional limits. Can be one of 0 = RMLFlags::POSITIONAL_LIMITS_IGNORE,
# 1 = RMLFlags::POSITIONAL_LIMITS_ERROR_MSG_ONLY, 2 = RMLFlags::POSITIONAL_LIMITS_ACTIVELY_PREVENT.
# Only available for Reflexxes Type_IV
positional_limits_behavior: 2

# The synchronization behavior of RML. Can be one of 0 = RMLFlags::PHASE_SYNCHRONIZATION_IF_POSSIBLE,
# 1 = RMLFlags::ONLY_TIME_SYNCHRONIZATION, 2 = RMLFlags::ONLY_PHASE_SYNCHRONIZATION, 3 = RMLFlags::NO_SYNCHRONIZATION
sync_behavior: 1
