--- name:default
# Cycle time in seconds
cycle_time: 0.02

# The limits for the joints
limits:
  names: ["J_Shoulder1_l", "J_Shoulder2_l", "J_UpperArm_l", "J_Elbow_l", "J_Forearm_l"]
  elements: [{max: {position: 1.74532925,  speed: 1.0, effort: 2.0}, min: {position: -0.872664625}}, # J_Shoulder1_l
             {max: {position: 0.087266462, speed: 1.0, effort: 2.0}, min: {position: -1.483529862}}, # J_Shoulder2_l
             {max: {position: 1.919862175, speed: 1.0, effort: 2.0}, min: {position: -1.919862175}}, # J_UpperArm_l
             {max: {position: 0.087266462, speed: 1.0, effort: 2.0}, min: {position: -1.832595712}}, # J_Elbow_l
             {max: {position: 1.570796325, speed: 1.0, effort: 2.0}, min: {position: -1.919862175}}] # J_Forearm_l


# Maximum change of acceleration. Size has to be the same as limits
max_jerk: [5,5,5,5,5]

# Set output effort as input for next cycle
override_input_effort: true

# Set output position as input for next cycle
override_input_position: true

# Set output speed as input for next cycle
override_input_speed: true

# Set output speed to fixed value every time. Setting this value to NaN means no override.
override_output_effort: false

# Set output speed to fixed value every time. Setting this value to NaN means no override.
override_output_speed: false

# Set target velocity forcefully to this value
override_target_velocity: .nan

# Behavior when reaching positional limits. Can be one of 0 = RMLFlags::POSITIONAL_LIMITS_IGNORE,
# 1 = RMLFlags::POSITIONAL_LIMITS_ERROR_MSG_ONLY, 2 = RMLFlags::POSITIONAL_LIMITS_ACTIVELY_PREVENT.
# Only available for Reflexxes Type_IV
positional_limits_behavior: 2

# The synchronization behavior of RML. Can be one of 0 = RMLFlags::PHASE_SYNCHRONIZATION_IF_POSSIBLE,
# 1 = RMLFlags::ONLY_TIME_SYNCHRONIZATION, 2 = RMLFlags::ONLY_PHASE_SYNCHRONIZATION, 3 = RMLFlags::NO_SYNCHRONIZATION
sync_behavior: 1
